export const GETDAILYWEATHERBYCOORDS = "GETDAILYWEATHERBYCOORDS";

export const GETCITYNAMEBYCOORDS = "GETCITYNAMEBYCOORDS"; 

export const GETCURRENTPOSITION = "GETCURRENTPOSITION";

export const GETCURRENTPOSITIONIP = "GETCURRENTPOSITIONIP";

export const GETERRORMESSAGE = "GETERRORMESSAGE";